#! /bin/bash

function errcho {
	>&2 echo $1
}

errcho "running in"

DEST_PATH=$1
CONFIG=$(cat)

errcho "loaded config: $CONFIG"

CHANNEL=$(echo $CONFIG | jq -r .source.env)
API_TOKEN=$(echo $CONFIG | jq -r .source.api_token)
LAST_VERSION=$(echo $CONFIG | jq -r .version.ref)

errcho "Channel: $CHANNEL"
errcho "ApiToken: $API_TOKEN"
errcho "Version: $LAST_VERSION"

CURRENT_VERSION=$(curl --request GET \
		                   --url "https://api.ionic.io/deploy/channels/${CHANNEL}" \
		                   --header "Authorization: Bearer ${API_TOKEN}" \
		                   | jq -r .data.deploy.uuid)

errcho "ran check for different version"

errcho "Old Version"
errcho "$LAST_VERSION"
errcho "New Version"
errcho "$CURRENT_VERSION"

errcho "====> finished 'in'"

printf '{ "version": {"ref": "%s"}, "metadata": [] }' "$CURRENT_VERSION"

